version: '3.9'

services:
  web:
    container_name: api
    build:
      context: .
      dockerfile: OlmaTech.Api/Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgresql;Database=OlmaTech;Port=5432;User Id=postgres;Password=12345;
    volumes:
      - /root/Sarvar/DB:/app/DB
      - /root/Sarvar/Files:/app/Files
    ports:
      - "8080:80"  # Map the container's port 80 to host port 5034
      - "8081:443"  # Map the container's port 443 to host port 7040
    networks:
      - olma

  db:
    container_name: postgresql
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: OlmaTech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - olma

volumes:
  postgres_data:

networks:
  olma:
    driver: bridge
